# Generated by Django 3.2.9 on 2021-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(max_length=50, verbose_name='Client_id')),
                ('firstname', models.CharField(max_length=50, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('age', models.IntegerField(max_length=50, verbose_name='Age')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
